### PR TITLE
Save and return unique image on each call

### PR DESCRIPTION
**Pull request by Mak-3**
will show the image which was given as an input. Address https://github.com/robmarkcole/yolov5-flask/issues/34

### CODE REVIEW

**Comment by robmarkcole** [comment]
Thanks for this PR! If multiple images are saved the image number increments? If so the api could return the latest image saved in that location

**Comment by Mak-3** [comment]
> Thanks for this PR! If multiple images are saved the image number increments? If so the api could return the latest image saved in that location

yeah working on the same thing we need to loop it or maintain a count will take some time

**Comment by robmarkcole** [comment]
Alternative is to create a unique directory inside images for every call, guaranteeing the image name is always the same. Directory name could be date time

**Comment by Mak-3** [comment]
> OK the solution is to use PIL to save the image with a known filename:
> ```python
>  results = model(im)  # inference
>  results.render()  # updates results.ims with boxes and labels
>  Image.fromarray(results.ims[0]).save("static/images/image0.jpg")
> ```
> should do it

Yup this works I tried it works fine for me

**Comment by robmarkcole** [comment]
closed by https://github.com/robmarkcole/yolov5-flask/pull/39

**Pull request closed without merging**
